lua require('plugins')
let g:vimwiki_list = [{'path': '~/vimwiki',
  \ 'path_html': '~/vimwiki_html',
  \ 'syntax': 'markdown',
  \ 'ext': '.md',
  \ 'custom_wiki2html': '~/vimwiki_html/wiki2html.sh'}]
